### ISSUE TITLE
Doesnt support android

### ISSUE THREAD

**Issue by Amurmurmur** [jacklam718/react-native-card-view#1]
Unfortunately it works fine on the iphone, but on android it doesnt show any borders at all :/

Here is the screenshot from both iOS simulator and Android emulator running the same view.
![screen shot 2016-08-04 at 13 46 05](https://cloud.githubusercontent.com/assets/8608333/17402215/ee53c47c-5a49-11e6-8049-4247dc7d9aa8.png)

**Comment by jacklam718** [comment]
Sorry @Amurmurmur I will investigate this issue.
Thank you for reporting this issue!

**Comment by Amurmurmur** [comment]
@jacklam718 Hey I've found a way to add shadows to the android version:
to your card style add this: elevation: 5,

Hope that helps to you and everyone!

Great component tho 👍

**Comment by jacklam718** [comment]
@Amurmurmur  Good Job!
